name: Tests check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js version from package.json
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run all tests (just unit)
        run: npm run test:unit

      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{ github.workspace }}/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
